# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ba1b599a0a13944cff5d89c4be62067c894aeb88f5673341c04ab5ae7974d188b58f02a685a33fb48f40437ad160054078a638477dc4ee40a968529740e597a

test:
  secret_key_base: 111b885c4e17cc20b069b973c7477e0cd982244c165f1fda39bd80943aff2b31f59e8a6a57e4506eea940dd6919751bb51c95ad8ac1644372e0dffb990527a68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
